SET NAMES 'UTF8MB4';
DROP DATABASE IF EXISTS extraordinarios;
CREATE DATABASE IF NOT EXISTS extraordinarios DEFAULT CHARACTER SET UTF8MB4;
USE extraordinarios;

CREATE TABLE profesor(
	id_prof INT PRIMARY KEY NOT NULL auto_increment,
	nombre VARCHAR(50) NOT NULL
);

CREATE TABLE materias (
    id_mat INT AUTO_INCREMENT PRIMARY KEY,
    semestre ENUM(
        '1', '2', '3', '4', '5', '6', '7', '8', '9') NOT NULL,
    creditos INT NOT NULL,
    nombre_materia VARCHAR(150) NOT NULL,
    clave_materia VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE vuelta(
	id_vuelta INT PRIMARY KEY NOT NULL auto_increment,
	num_vuelta VARCHAR(25)
);

CREATE TABLE historico(
	id_hist INT PRIMARY KEY NOT NULL auto_increment,
	id_prof INT NOT NULL,
	id_mat INT NOT NULL,
	semestre VARCHAR(6) NOT NULL,
	id_vuelta INT NOT NULL,
	FOREIGN KEY (id_prof) REFERENCES profesor(id_prof),
	FOREIGN KEY (id_mat) REFERENCES materias(id_mat),
	FOREIGN KEY (id_vuelta) REFERENCES vuelta(id_vuelta)

);

INSERT INTO profesor(nombre) VALUES
("ABURTO CAMACHO BLANCA PAMELA"),
("AGUILAR HERNANDEZ JOSE FRANCISCO"),
("ALBA VILLA BELEN ANAID"),
("ALMANZAR VAZQUEZ MARIA GUADALUPE"),
("ALVAREZ SORIANO MANUEL ALEJANDRO"),
("ANAYA MANILA DZOARA IVETTE"),
("ARELLANO OROZCO JUAN MANUEL"),
("ARELLANO RIVERA ESTEBAN"),
("AYALA PEÑA ESTEBAN"),
("BERNAL DIAZ ARCELIA"),
("BLANCO BAUTISTA ROBERTO"),
("CAMACHO ALVAREZ JUAN CARLOS"),
("CAMPOS BRAVO JORGE IVAN"),
("CANDELARIO ALAVEZ JORGE LUIS"),
("CANTO GALLO RAFAEL"),
("CERVANTES PATIÑO MOISES"),
("CHIAPA MONROY CUAUHTEMOC"),
("COLUNGA VAZQUEZ MATILDE"),
("CRUZ LUEVANO BLANCA ESTELA"),
("FALCON ARELLANO BERENICE ITZE"),
("FERIA VICTORIA MARIA ANGELICA"),
("GALICIA RANGEL GILDA"),
("GARCIA GUZMAN ENRIQUE"),
("GARCIA MONROY JOSE ANTONIO"),
("GARCIA VILLANUEVA MA. DEL PILAR"),
("GARIBAY PEDRAZA ALMA LILIA"),
("GASTALDI PEREZ JUAN"),
("GERMAN ROSAS CESAR FRANCISCO"),
("GONZALEZ AYALA LUIS ENRIQUE"),
("GONZALEZ BETANCOURT RAFAEL"),
("GONZALEZ HERNANDEZ GERARDO"),
("GONZALEZ HERNANDEZ MARIA GABRIELA"),
("GONZALEZ MAXINEZ DAVID JAIME"),
("GOYTIA HERRERA MARCO INTI"),
("GRADA HUERTA IVAN"),
("GUERRERO SANTAMARIA EFREN"),
("GUTIERREZ CASTILLO ALMA ROSA"),
("GUTIERREZ LOPEZ FELIPE DE JESUS"),
("GUTIERREZ OROZCO RICARDO ARTURO"),
("HERNANDEZ AUDELO LEOBARDO"),
("HERNANDEZ CABRERA JESUS"),
("HERNANDEZ CONTRERAS JUAN MANUEL"),
("HERNANDEZ GALICIA SALOMON"),
("HERNANDEZ HERNANDEZ MARTIN"),
("HERNANDEZ LOPEZ SERGIO"),
("ISLAS HERNANDEZ CLARA YAHAIRA"),
("JUAREZ PALMA JOSE GIL"),
("JUAREZ ROBLES ELIZABETH"),
("LOPEZ CARRETO JUAN MANUEL"),
("LOZANO MENDEZ EFREN"),
("MARTINEZ ROMERO JONATHAN"),
("MENDOZA GONZALEZ OMAR"),
("MONDRAGON ESCOBAR ALFREDO"),
("MONTERROSA ESCOBAR AMILCAR AMADO"),
("MORALES GONZALEZ JORGE CARLOS"),
("MORALES PALAFOX EDGAR"),
("NAVARRO DIAZ RAMON"),
("NERIA OROZCO ERIK DE JESUS"),
("OCAMPO ALVAREZ ARTURO"),
("OLIVER MORALES CARLOS"),
("ORDOÑEZ ROSALES MARTIN"),
("ORTEGA NAVA CARLOS FERNANDO"),
("ORTIZ CORDERO GABRIEL"),
("ORTIZ JIMENEZ MARIA ELENA"),
("PALMA LOPEZ DANIEL FERNANDO"),
("PARRALES CASTAÑEDA CARLOS ALBERTO"),
("PATIÑO RODRIGUEZ RAMON"),
("PELCASTRE RAMIREZ GLORIA SAMANTHA"),
("PEÑALOZA ROMERO ERNESTO"),
("PEREZ GUZMAN ALEJANDRO"),
("PEREZ MEDEL MARCELO"),
("PEREZ MUÑOZ ANTONIO GERARDO"),
("PEREZ PAZ EDUARDO"),
("PEREZ VALDES JOEL ALFREDO"),
("PICCINELLI BOCCHI GABRIELLA"),
("QUINTERO CERVANTES JOSE MANUEL"),
("QUIROZ ALMARAZ SERGIO"),
("RAMIREZ CRUZ JOSE LUIS"),
("RAMIREZ LAZOS ESTEBAN"),
("RAMOS MARQUEZ JUAN CARLOS"),
("REYES CRUZ ANA CLAUDIA"),
("REYES TECONTERO NORMA"),
("RODRIGUEZ GARCIA ARTURO"),
("ROMERO ANDALON JESUS ANGEL"),
("ROMERO UGALDE MARTIN MANUEL"),
("SANCHEZ HERNANDEZ MIGUEL ANGEL"),
("SANCHEZ MORALES VICTOR MANUEL"),
("SEGURA RAUDA MINERVA"),
("SOBERANES JAIME ROBERTO MISAEL"),
("SOLIS ALCANTAR EVERARDO"),
("SUAREZ HERRERA ALEJANDRO"),
("TORRES RODRIGUEZ GERARDO"),
("TORRES TORRES FAUSTO"),
("UGALDE LOPEZ JUDITH"),
("VAZQUEZ MORALES RODOLFO"),
("VELASCO AGUSTIN AARON"),
("VERDE CRUZ ABEL"),
("VERDUZCO RODRIGUEZ MARIANA"),
("VIDAL CASTRO RICARDO ADOLFO"),
("VIEYRA REBOYO LUIS ARMANDO");


-- Plan 2020
INSERT INTO materias (semestre, creditos, nombre_materia, clave_materia) VALUES
('1', 9, 'GEOMETRIA ANALITICA', '1108'),
('1', 9, 'CALCULO DIFERENCIAL E INTEGRAL', '1109'),
('1', 9, 'ALGEBRA', '1110'),
('1', 9, 'COMPUTADORAS Y PROGRAMACION', '1111'),
('1', 6, 'INTRODUCCION A LA INGENIERIA EN COMPUTACION', '1112');

-- 2
INSERT INTO materias (semestre, creditos, nombre_materia, clave_materia) VALUES
('2', 9, 'ALGEBRA LINEAL', '0062'),
('2', 9, 'CALCULO VECTORIAL', '0063'),
('2', 8, 'PROGRAMACION ORIENTADA A OBJETOS', '1203'),
('2', 8, 'COMUNICACION', '1209'),
('2', 8, 'EMPRENDIMIENTO 1', '1210'),
('2', 3, 'TALLER DE CREATIVIDAD E INNOVACION', '1211');

-- TERCER
INSERT INTO materias (semestre, creditos, nombre_materia, clave_materia) VALUES
('3', 11, 'ELECTRICIDAD Y MAGNETISMO (L)', '0071'),
('3', 8, 'ESTRUCTURA DE DATOS', '0190'),
('3', 9, 'METODOS NUMERICOS', '0480'),
('3', 9, 'ECUACIONES DIFERENCIALES', '1303'),
('3', 8, 'EMPRENDIMIENTO 2', '1311');

-- 3
INSERT INTO materias (semestre, creditos, nombre_materia, clave_materia) VALUES
('4', 9, 'PROBABILIDAD Y ESTADISTICA', '0712'),
('4', 8, 'BASES DE DATOS 1', '1417'),
('4', 8, 'EMPRENDIMIENTO 3', '1418'),
('4', 9, 'MATEMATICAS DISCRETAS', '1419'),
('4', 10, 'DISPOSITIVOS ELECTRONICOS (L)', '1522');

-- 5
INSERT INTO materias (semestre, creditos, nombre_materia, clave_materia) VALUES
('5', 8, 'LENGUAJES FORMALES Y AUTOMATAS', '0442'),
('5', 9, 'DISEÑO Y ANALISIS DE ALGORITMOS', '1500'),
('5', 8, 'ADMINISTRACION DE PROYECTOS', '1503'),
('5', 9, 'PROGRAMACION WEB 1', '1504'),
('5', 10, 'DISEÑO LOGICO (L)', '1521');

-- 6
INSERT INTO materias (semestre, creditos, nombre_materia, clave_materia) VALUES
('6', 8, 'COMPILADORES', '0434'),
('6', 8, 'SISTEMAS OPERATIVOS', '0840'),
('6', 10, 'DISEÑO DE SISTEMAS DIGITALES (L)', '1604'),
('6', 8, 'INGENIERIA DE SOFTWARE', '1605');

-- 7
INSERT INTO materias (semestre, creditos, nombre_materia, clave_materia) VALUES
('7', 8, 'SISTEMAS DE INFORMACION', '0789'),
('7', 9, 'PROGRAMACION WEB 2', '1718'),
('7', 10, 'REDES DE COMPUTADORAS 1 (L)', '1719'),
('7', 10, 'MICROPROCESADORES Y MICROCONTROLADORES (L)', '1800');

-- 8
INSERT INTO materias (semestre, creditos, nombre_materia, clave_materia) VALUES
('8', 8, 'BASES DE DATOS 2', '1810'),
('8', 9, 'PROGRAMACION MOVIL 1', '1812'),
('8', 8, 'REDES DE COMPUTADORAS 2', '1813'),
('8', 8, 'HABILIDADES DIRECTIVAS', '1917');

-- 9
INSERT INTO materias (semestre, creditos, nombre_materia, clave_materia) VALUES
('9', 8, 'INTELIGENCIA ARTIFICIAL', '0406'),
('9', 8, 'SEGURIDAD INFORMATICA', '1705'),
('9', 8, 'MINERIA DE DATOS', '1908');

-- Plan 2008
-- 2
INSERT INTO materias (semestre, creditos, nombre_materia, clave_materia) VALUES
('2', 6, 'COMUNICACION ORAL Y ESCRITA', '1202'),
('2', 8, 'ADMINISTRACION CONTABILIDAD Y COSTOS', '0019');

-- TERCER
INSERT INTO materias (semestre, creditos, nombre_materia, clave_materia) VALUES
('3', 8, 'INTRODUCCION A LA ECONOMIA', '0232');

-- 4
INSERT INTO materias (semestre, creditos, nombre_materia, clave_materia) VALUES
('4', 8, 'INVESTIGACION DE OPERACIONES Y SISTEMAS', '1410'),
('4', 8, 'INGENIERIA ECONOMICA', '1405'),
('4', 9, 'ESTRUCTURAS DISCRETAS', '1401'),
('4', 10, 'ANALISIS DE CIRCUITOS ELECTRICOS (L)', '0024');

-- 5
INSERT INTO materias (semestre, creditos, nombre_materia, clave_materia) VALUES
('5', 8, 'PROGRAMACION DE SISTEMAS', '0633'),
('5', 9, 'DISPOSITIVOS ELECTRONICOS (L)', '0138'),
-- Tambien es optativa en el plan 2020
('5', 10, 'MEDICION E INSTRUMENTACION', '1715');

-- 6
INSERT INTO materias (semestre, creditos, nombre_materia, clave_materia) VALUES
('6', 10, 'DISEÑO LOGICO (L)', '1720'),
('6', 10, 'SISTEMAS DE COMUNICACIONES (L)', '1603'),
-- Optativa plan 2020
('6', 10, 'CALIDAD', '2129'),
('6', 8, 'INGENIERIA DE SOFTWARE I', '1600');

-- 7
INSERT INTO materias (semestre, creditos, nombre_materia, clave_materia) VALUES
('7', 8, 'DINAMICA DE SISTEMAS FISICOS', '0129'),
('7', 9, 'BASES DE DATOS I', '1702'),
('7', 10, 'REDES DE COMPUTADORAS I (L)', '1704'),
('7', 10, 'DISEÑO DE SISTEMAS DIGITALES', '1721');

-- 8
INSERT INTO materias (semestre, creditos, nombre_materia, clave_materia) VALUES
('8', 8, 'ORGANIZACION Y ADMINISTRACION DE CENTROS DE COMPUTO', '1801'),
('8', 9, 'SISTEMAS DE CONTROL ', '1802');

-- 9
INSERT INTO materias (semestre, creditos, nombre_materia, clave_materia) VALUES
('9', 8, 'GESTION DE REDES DE COMPUTADORAS (L)', '1914');


INSERT INTO vuelta(num_vuelta) VALUES
("Primera"),
("Segunda");
